server:
  port: 8085
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        webmvc: 
          routes:
            - id: user-service-route
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - CircuitBreaker=userServiceCB,forward:/fallback/users
           
