server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      mvc: 
        routes:
          - id: user-service-route
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/users/**


