server:
  forward-headers-strategy: framework
  tomcat:   
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  
spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:    
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    # Настройки Hibernate
    hibernate:     
      ddl-auto: update

   
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:

    topic: user-topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 


